<?php

function common_elements_theme() {
  return array(
    'header' => array(
      'variables' => array('page' => array()),
      'template' => 'header',
      'preprocess functions' => array('common_elements_page_variables'),
    ),
    'footer' => array(
      'variables' => array('page' => array()),
      'template' => 'footer',
      'preprocess functions' => array('common_elements_page_variables'),
    ),
  );
}

function common_elements_element_info() {
  return array(
    'header' => array(
      '#theme' => 'header',
    ),
    'footer' => array(
      '#theme' => 'footer',
    ),
  );
}

function common_elements_page_build(&$page) {
  $page['header'] = element_info('header');
  $page['footer'] = element_info('footer');
}

function common_elements_page_alter(&$page) {
  // Pull out the default page variables.
  $filtered_page = array_diff_key($page, array('header' => '', 'footer' => ''));
  // Ensure regions receive the correct theme_wrappers.
  system_page_alter($filtered_page);

  // Set up the page variables for header and footer.
  $page['header']['#page'] = $filtered_page;
  $page['footer']['#page'] = $filtered_page;
}

function common_elements_page_variables(&$variables) {
  // Store the theme_hook_suggestions, as we'll revert to them later.
  $suggestions = $variables['theme_hook_suggestions'];

  // Loop through the preprocess_page hooks, and apply them.
  $hooks = theme_get_registry();
  foreach ($hooks['page']['preprocess functions'] as $preprocess) {
    if (function_exists($preprocess)) { $preprocess($variables, 'preprocess_page'); }
  }
  foreach ($hooks['page']['process functions'] as $process) {
    if (function_exists($process)) { $process($variables, 'process_page'); }
  }

  // Revert back to the original theme_hook_suggestions.
  $variables['theme_hook_suggestions'] = $suggestions;
}
