<?php

function common_elements_theme() {
  return array(
    'header' => array(
      'variables' => array('region' => array()),
      'template' => 'header',
      'preprocess functions' => array('common_elements_page_variables'),
    ),
    'footer' => array(
      'variables' => array('region' => array()),
      'template' => 'footer',
      'preprocess functions' => array('common_elements_page_variables'),
    ),
  );
}

function common_elements_element_info() {
  return array(
    'header' => array(
      '#theme' => 'header',
    ),
    'footer' => array(
      '#theme' => 'footer',
    ),
  );
}

function common_elements_page_build(&$page) {
  $page['header'] = element_info('header');
  if (empty($page['region_header']) === FALSE) {
    $page['header']['#region'] = $page['region_header'];
  }
  $page['footer'] = element_info('footer');
  if (empty($page['region_footer']) === FALSE) {
    $page['footer']['#region'] = $page['region_footer'];
  }
}

function common_elements_page_variables(&$variables) {
  // Store the theme_hook_suggestions, as we'll revert to them later.
  $suggestions = $variables['theme_hook_suggestions'];

  // Stub in some page data, so that our variables are set properly.
  $variables['page'] = array();
  $variables['page']['#show_messages'] = FALSE;

  // Loop through the preprocess_page hooks, and apply them.
  $hooks = theme_get_registry();
  foreach ($hooks['page']['preprocess functions'] as $preprocess) {
    if (function_exists($preprocess)) { $preprocess($variables, 'preprocess_page'); }
  }

  // Revert back to the original theme_hook_suggestions.
  $variables['theme_hook_suggestions'] = $suggestions;
}
